### PR TITLE
Fixed a typo in tutorial.json file 

### PR DESCRIPTION
**Pull request by Jy411**
Renamed the sentence from:

>  Turns out you want some different font for the website. From here, create roboto-bold.woff in your new fonts folder. You can put the path in front of the filename of where you want it to go.

to

>  Turns out you want some different **fonts** for the website. From here, create roboto-bold.woff in your new fonts folder. You can put the path in front of the filename of where you want it to go.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #43491

### CODE REVIEW

**Comment by moT01** [comment]
Thanks for your interest in contributing @Jy411. That's not quite how these tutorials work. I am in the process of creating documentation for working on these. Here's part of it that will help you:

#### Prerequisites
[Coderoad CLI](https://www.npmjs.com/package/@coderoad/cli/v/0.8.0) - `npm install -g @coderoad/cli` - I'm having trouble with the latest version (0.8.0) right now - if you can't do `coderoad --version` after installing, you can try `npm install -g @coderoad/cli@0.7.0` to use that version.

#### If you are only making changes to the main branch:
This mostly includes instructional/grammar changes or fixes in the `TUTORIAL.md` file. It also includes changes to `coderoad.yaml`. You never need to modify the `tutorial.json` file directly
- Create a new branch off main
- Make and commit your changes - try to use a descriptive message (`fix: typo`)
- Run `coderoad build` to recreate the `tutorial.json` file
- Commit the changes - use `update json` for the message
- Make a PR

**Comment by riadh26** [comment]
@moT01 following your instructions on how to make the changes, that didn't work, as when running the command `coderoad build` i get the following error :
```
Building CodeRoad tutorial.json...
Error loading commits:
Code branch "v1.0.0" not found
```
i'm using version 0.7.0 of coderoad/cli

**Comment by moT01** [comment]
Try creating the branch locally first @riadh26 - should be something like `git branch v1.0.0 upstream/v1.0.0` I think
Let me know if it works. I think it should - I will have to add that to the instructions 👍

**Comment by riadh26** [comment]
Yes it works @moT01 thank you, just to note `git branch v1.0.0 origin/v1.0.0`

**Comment by moT01** [comment]
origin or upstream would be whatever you named the remote 👍 upstream is kind of the standard, I believe, for remotes that point to the repo you have forked from - but whatever works 👍

**Comment by moT01** [comment]
This has been fixed via another PR so it's safe to close this. Thanks for the help everyone 🎉

**Pull request closed without merging**
