### PR TITLE
Fix typo "fonts" instead of "font's"

### PR DESCRIPTION
**Pull request by kmbenjel**
Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Screenshot from 2022-01-01 15-39-05

Closes #XXXXX

### CODE REVIEW

**Review by gikf — CHANGES_REQUESTED** [review]
Changes in this repository require following specific workflow, detailed guidelines how to contribute to it can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Please refer to the parts about making changes on the `main` branch.

**Comment by moT01** [comment]
Thanks for pointing this out @kmbenjel 👍 I added this fix to a recent update, so we won't need this PR anymore. Thanks and happy coding 🎉

**Comment by kmbenjel** [comment]
Eh, thank you and sorry,
I'll get more involved in the contribution as it should be.

**Comment by moT01** [comment]
No need to apologize - sorry if I cut you off from working on this. These are little tricky to contribute to. I was working on some other fixes and decided to just fix that typo along with it. I'm sure there's plenty of other typos - if you come across any, feel free to make another PR.

**Comment by kmbenjel** [comment]
Well done of course, thank you so much, I'll be in!

**Pull request closed without merging**
