### PR TITLE
fix: typo from 'Remeber' to 'Remember'

### PR DESCRIPTION
**Pull request by Heizenburg**
Fix typo from 'Remeber' -> 'Remember'

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Review by gikf — CHANGES_REQUESTED** [review]
This tutorial is using CodeRoad VS Code extension, specific guidelines how to contribute to them can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Making PR for this issue will require following parts referring to making changes on the `main` branch.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.


Happy contributing.

**Comment by Heizenburg** [comment]
Noted...

**Comment by gikf** [comment]
Hey @Heizenburg,

any progress on this?

**Comment by Heizenburg** [comment]
Hey there,

Been on vacation but I'll definitely have the PR done by today.

Thanks, Thato.

**Comment by Heizenburg** [comment]
@gikf done.

**Comment by gikf** [comment]
Did you push the new changes to this branch? I'm not seeing other commits than the initial one.

**Comment by Heizenburg** [comment]
I created a new pull request.

**Pull request closed without merging**
