### PR TITLE
version 1.0.3 ready for review

### PR DESCRIPTION
**Pull request by bellhuffstutler**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #46215

### CODE REVIEW

**Comment by gikf** [comment]
Hey @bellhuffstutler

Thank you for opening this pull request.

Looks like something went wrong in the second commit and not needed files were added. Could you remove them from PR?

For the version branch - https://github.com/bellhuffstutler/learn-bash-by-building-a-boilerplate/tree/v1.0.3, changes from the last commit https://github.com/bellhuffstutler/learn-bash-by-building-a-boilerplate/commit/2e5669a10d37a193647d965f51d16c76abf3c469 need to be moved to commit adding these files. In this case that's `INIT` - the same as other changes that were made to the tests.

**Comment by bellhuffstutler** [comment]
absolutely yeah ill redo it after some coffee!

Sorry about that

**Comment by bellhuffstutler** [comment]
Okay! I have the codebase sorted out now so it should be good. 

Not sure why all those extra bits were there, but they are gone now and I followed the steps so everything should be correct now

**Comment by gikf** [comment]
There's still something weird going on the version branch. See https://github.com/bellhuffstutler/learn-bash-by-building-a-boilerplate/commits/v1.0.3?after=e8774fbd82c4f465f8455b3e49ffb39f6f751af6+139&branch=v1.0.3&qualified_name=refs%2Fheads%2Fv1.0.3 and https://github.com/bellhuffstutler/learn-bash-by-building-a-boilerplate/commits/v1.0.3

It appears as if the version branch was put onto the main branch, compare also the INIT commit from 1.0.3 https://github.com/bellhuffstutler/learn-bash-by-building-a-boilerplate/tree/0e2f7acc58dc9640add3847de66d127d2e28e690 and 1.0.2 https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/tree/31e22639d96f3f21e2e43c91d4943298e59d76de

**Comment by bellhuffstutler** [comment]
I might just have to completely try again because I have no idea what's going on here and it would probably be easier to just do it all fresh from the top. 

I'm just so confused and have no idea what is going on, and it seems like the best solution. I'll try again later today after just completely redoing it from scratch

**Comment by gikf** [comment]
Starting fresh sounds reasonable.

Let us know if you'd need help with it.

**Pull request closed without merging**
